# Generated by Django 4.0.3 on 2022-04-08 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_nanny_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='appliednanny',
            fields=[
                ('applyid', models.AutoField(primary_key=True, serialize=False)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobs')),
                ('nannyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nanny')),
            ],
        ),
    ]
