# Generated by Django 4.0.3 on 2022-04-08 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_nanny_user'),
        ('app', '0002_nanny_jobs'),
    ]

    operations = [
    ]
