# Generated by Django 4.0.3 on 2022-04-08 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_merge_0002_alter_nanny_user_0002_nanny_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience_req',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=16)),
                ('fromparent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample1', to=settings.AUTH_USER_MODEL)),
                ('tositter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='appliednanny',
            fields=[
                ('applyid', models.AutoField(primary_key=True, serialize=False)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobs')),
                ('nannyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nanny')),
            ],
        ),
    ]
