# Generated by Django 4.0.3 on 2022-04-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobs_experience_req_alter_jobs_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(default='', max_length=16),
        ),
    ]
