# Generated by Django 4.0.3 on 2022-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliednanny',
            name='status',
            field=models.CharField(default='pending', max_length=16),
        ),
    ]
